### ISSUE TITLE
rendering fails after adding points with mouse and clicking stop/continue instead of start/restart

### ISSUE THREAD

**Issue by likethisinstead** [parano/GeneticAlgorithm-TSP#1]
-> F5/reload
-> start
-> stop
-> add 1+ points with mouse
-> stop/continue
generation/mutation/best value are updating, but the updated paths aren't rendered in canvas

this is due to the following snippet in src/main.js:

```
if(best.length === points.length) {
    drawLines(best);
}
```

**Comment by likethisinstead** [comment]
same behaviour when adding random points using the button then clicking stop/continue

the same patch [https://github.com/parano/GeneticAlgorithm-TSP/pull/2] will address both

**Comment by parano** [comment]
@likethisinstead thanks for fixing this!
