### ISSUE TITLE
Suggest: Create nodejs package

### ISSUE THREAD

**Issue by thucnc** [parano/GeneticAlgorithm-TSP#3]
May you guide me to create nodejs package from your algorithm implementation or how to use it in nodejs ? Thanks a lot.

**Comment by mourner** [comment]
I'll take a stab at this.

**Comment by parano** [comment]
@thucnc sadly the current implementation isn't super easy to re-use as a package, I will try make the interface more generic and make sure it's scoped correctly. Then I will create a nodejs package for it.
