### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by mourner** [parano/GeneticAlgorithm-TSP#4]
@parano Thank you for a wonderful project! Since you've published it on GitHub, I assume you were meaning to publish it as open source. If so, can you choose a license for your published code and put the text in the repo (in a `LICENSE` file)? http://choosealicense.com/ is helpful for choosing a license.

**Comment by parano** [comment]
@mourner thanks for pointing this out, I'm going to add a license file to the repo.
